# Use an OpenJDK 7 base image
FROM arm64v8/openjdk:7-jdk

# Set the working directory
WORKDIR /app

# Copy local files to the working directory in the container
COPY . /app

# Set the command to run the application (optional)
# CMD ["java", "-jar", "your-application.jar"]

# Expose a port if needed
# EXPOSE 8080
